<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<OutputPath>..\..\Mods\VNPE\Assemblies\</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath Condition="Exists('..\..\..\..\..\..\..\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll')">..\..\..\..\..\..\..\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
			<HintPath Condition="Exists('\Program Files (x86)\Steam\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll')">\Program Files (x86)\Steam\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath Condition="Exists('..\..\..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll')">..\..\..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
			<HintPath Condition="Exists('\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll')">\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PipeSystem">
			<HintPath Condition="Exists('..\..\..\..\..\..\..\workshop\content\294100\2023507013\1.4\Assemblies\PipeSystem.dll')">..\..\..\..\..\..\..\workshop\content\294100\2023507013\1.4\Assemblies\PipeSystem.dll</HintPath>
			<HintPath Condition="Exists('\Program Files (x86)\Steam\steamapps\workshop\content\294100\2023507013\1.4\Assemblies\PipeSystem.dll')">\Program Files (x86)\Steam\steamapps\workshop\content\294100\2023507013\1.4\Assemblies\PipeSystem.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath Condition="Exists('..\..\..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll')">..\..\..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
			<HintPath Condition="Exists('\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll')">\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath Condition="Exists('..\..\..\..\..\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll')">..\..\..\..\..\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
			<HintPath Condition="Exists('\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll')">\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="VNPE">
			<HintPath Condition="Exists('..\..\..\..\..\..\..\workshop\content\294100\2920385763\1.4\Assemblies\VNPE.dll')">..\..\..\..\..\..\..\workshop\content\294100\2920385763\1.4\Assemblies\VNPE.dll</HintPath>
			<HintPath Condition="Exists('\Program Files (x86)\Steam\steamapps\workshop\content\294100\2920385763\1.4\Assemblies\VNPE.dll')">\Program Files (x86)\Steam\steamapps\workshop\content\294100\2920385763\1.4\Assemblies\VNPE.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GeneExtractorTiers\GeneExtractorTiers.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>

</Project>